/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as draftIerc1822UpgradeableSol from "./draft-IERC1822Upgradeable.sol";
export type { draftIerc1822UpgradeableSol };
export type { IERC4626Upgradeable } from "./IERC4626Upgradeable";
