/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IInsureOracle,
  IInsureOracleInterface,
} from "../../../contracts/interfaces/IInsureOracle";

const _abi = [
  {
    inputs: [
      {
        internalType: "string[]",
        name: "assets",
        type: "string[]",
      },
    ],
    name: "getMultiPrices",
    outputs: [
      {
        internalType: "uint256[]",
        name: "",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "asset",
        type: "string",
      },
    ],
    name: "getPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IInsureOracle__factory {
  static readonly abi = _abi;
  static createInterface(): IInsureOracleInterface {
    return new utils.Interface(_abi) as IInsureOracleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IInsureOracle {
    return new Contract(address, _abi, signerOrProvider) as IInsureOracle;
  }
}
