/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IAddressesProvider__factory } from "./IAddressesProvider__factory";
export { IRiskPool__factory } from "./IRiskPool__factory";
export { IStdReference__factory } from "./IStdReference__factory";
