/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  AccessRestricted,
  AccessRestrictedInterface,
} from "../../../contracts/access/AccessRestricted";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint8",
        name: "version",
        type: "uint8",
      },
    ],
    name: "Initialized",
    type: "event",
  },
];

export class AccessRestricted__factory {
  static readonly abi = _abi;
  static createInterface(): AccessRestrictedInterface {
    return new utils.Interface(_abi) as AccessRestrictedInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AccessRestricted {
    return new Contract(address, _abi, signerOrProvider) as AccessRestricted;
  }
}
