/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAddressesProvider } from "./IAddressesProvider";
export type { IRiskPool } from "./IRiskPool";
export type { IStdReference } from "./IStdReference";
