/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AddressesProvider } from "./AddressesProvider";
export type { ParametersProvider } from "./ParametersProvider";
