/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockOracle__factory } from "./MockOracle__factory";
export { USDC__factory } from "./USDC__factory";
